services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: cargo_target
        target: /workspace/target
    stdin_open: true
    tty: true

volumes:
  cargo_target: