name: Develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    name: Run tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - uses: actions/checkout@v4
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Test and build
        run: |
          cargo check
          cargo test
          cargo build --release
